/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package prepaidwaterbillingsystem;
import java.sql.*;
import java.text.MessageFormat;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;
import static prepaidwaterbillingsystem.Loginform.getUsername;
import java.util.*;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import static prepaidwaterbillingsystem.Loginform.getUsername;
import static prepaidwaterbillingsystem.Loginform.setUsername;
import static prepaidwaterbillingsystem.PREPAIDWATERBILLINGSYSTEM.getMeterno;

/**
 *
 * @author kelvinolang
 */
public class tab2 extends javax.swing.JFrame {

    // calculates ammount of water tokens
        int Rate = 18;
        

    public int getRate() {
        return Rate;
    }
    Connection conn = null;
    PreparedStatement stmt = null;
    

    /**
     * Creates new form tab2
     */
    public tab2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Header2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        User2 = new javax.swing.JPanel();
        user2 = new javax.swing.JLabel();
        UserMenu = new javax.swing.JPanel();
        Dashboard = new javax.swing.JPanel();
        dashboard = new javax.swing.JLabel();
        Home = new javax.swing.JPanel();
        home = new javax.swing.JLabel();
        PayBill = new javax.swing.JPanel();
        paybill = new javax.swing.JLabel();
        EditProfile = new javax.swing.JPanel();
        editprofile = new javax.swing.JLabel();
        ContactUs = new javax.swing.JPanel();
        contactus = new javax.swing.JLabel();
        LogOut = new javax.swing.JPanel();
        logout = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        STATEMENTS = new javax.swing.JButton();
        BANKACCOUNT = new javax.swing.JButton();
        MPESA2 = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        mpesa = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        PHONENO = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        phoneno = new javax.swing.JTextField();
        ENTERAMOUNT = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        amount = new javax.swing.JTextField();
        pay = new javax.swing.JButton();
        bankaccount = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        enteraccountno = new javax.swing.JTextField();
        enteramount = new javax.swing.JTextField();
        PAY = new javax.swing.JButton();
        statements = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        printstatement = new javax.swing.JTable();
        showdata = new javax.swing.JButton();
        export = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Header2.setBackground(new java.awt.Color(51, 51, 255));

        jLabel5.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("CLEAN WATER COMPANY");

        jLabel6.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Your Trusted Water Supply");

        User2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                User2MouseClicked(evt);
            }
        });

        user2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        user2.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Desktop\\Icons\\icons8-user-30.png")); // NOI18N
        user2.setText("User");

        javax.swing.GroupLayout User2Layout = new javax.swing.GroupLayout(User2);
        User2.setLayout(User2Layout);
        User2Layout.setHorizontalGroup(
            User2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(User2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(user2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        User2Layout.setVerticalGroup(
            User2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(User2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(user2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout Header2Layout = new javax.swing.GroupLayout(Header2);
        Header2.setLayout(Header2Layout);
        Header2Layout.setHorizontalGroup(
            Header2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Header2Layout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addGroup(Header2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 151, Short.MAX_VALUE)
                .addComponent(User2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );
        Header2Layout.setVerticalGroup(
            Header2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Header2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Header2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(User2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        getContentPane().add(Header2, new org.netbeans.lib.awtextra.AbsoluteConstraints(213, 0, 720, 130));

        UserMenu.setBackground(new java.awt.Color(51, 51, 255));

        Dashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DashboardMouseClicked(evt);
            }
        });

        dashboard.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        dashboard.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Desktop\\Icons\\icons8-menu-24.png")); // NOI18N
        dashboard.setText("Dashboard");

        javax.swing.GroupLayout DashboardLayout = new javax.swing.GroupLayout(Dashboard);
        Dashboard.setLayout(DashboardLayout);
        DashboardLayout.setHorizontalGroup(
            DashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DashboardLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(dashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        DashboardLayout.setVerticalGroup(
            DashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DashboardLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dashboard, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                .addContainerGap())
        );

        Home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HomeMouseClicked(evt);
            }
        });

        home.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        home.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Desktop\\Icons\\icons8-home-24.png")); // NOI18N
        home.setText("Home");

        javax.swing.GroupLayout HomeLayout = new javax.swing.GroupLayout(Home);
        Home.setLayout(HomeLayout);
        HomeLayout.setHorizontalGroup(
            HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HomeLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(home, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        HomeLayout.setVerticalGroup(
            HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HomeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(home, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                .addContainerGap())
        );

        PayBill.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PayBillMouseClicked(evt);
            }
        });

        paybill.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        paybill.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Desktop\\Icons\\icons8-card-payment-16.png")); // NOI18N
        paybill.setText("Pay Bill");

        javax.swing.GroupLayout PayBillLayout = new javax.swing.GroupLayout(PayBill);
        PayBill.setLayout(PayBillLayout);
        PayBillLayout.setHorizontalGroup(
            PayBillLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PayBillLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(paybill, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        PayBillLayout.setVerticalGroup(
            PayBillLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PayBillLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(paybill, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                .addContainerGap())
        );

        EditProfile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EditProfileMouseClicked(evt);
            }
        });

        editprofile.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        editprofile.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Desktop\\Icons\\icons8-user-30.png")); // NOI18N
        editprofile.setText("Edit Profile");

        javax.swing.GroupLayout EditProfileLayout = new javax.swing.GroupLayout(EditProfile);
        EditProfile.setLayout(EditProfileLayout);
        EditProfileLayout.setHorizontalGroup(
            EditProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EditProfileLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(editprofile, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        EditProfileLayout.setVerticalGroup(
            EditProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EditProfileLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(editprofile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        ContactUs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ContactUsMouseClicked(evt);
            }
        });

        contactus.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        contactus.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Desktop\\Icons\\icons8-man-30.png")); // NOI18N
        contactus.setText("Contact Us");

        javax.swing.GroupLayout ContactUsLayout = new javax.swing.GroupLayout(ContactUs);
        ContactUs.setLayout(ContactUsLayout);
        ContactUsLayout.setHorizontalGroup(
            ContactUsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContactUsLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(contactus, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        ContactUsLayout.setVerticalGroup(
            ContactUsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContactUsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(contactus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        LogOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogOutMouseClicked(evt);
            }
        });

        logout.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        logout.setText("Log Out");

        javax.swing.GroupLayout LogOutLayout = new javax.swing.GroupLayout(LogOut);
        LogOut.setLayout(LogOutLayout);
        LogOutLayout.setHorizontalGroup(
            LogOutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LogOutLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        LogOutLayout.setVerticalGroup(
            LogOutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LogOutLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout UserMenuLayout = new javax.swing.GroupLayout(UserMenu);
        UserMenu.setLayout(UserMenuLayout);
        UserMenuLayout.setHorizontalGroup(
            UserMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UserMenuLayout.createSequentialGroup()
                .addGroup(UserMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(UserMenuLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(UserMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Dashboard, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Home, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(PayBill, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(EditProfile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ContactUs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(LogOut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jSeparator1))
                .addContainerGap())
        );
        UserMenuLayout.setVerticalGroup(
            UserMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UserMenuLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(Dashboard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(Home, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(PayBill, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(EditProfile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(ContactUs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(LogOut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(UserMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 520));

        STATEMENTS.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        STATEMENTS.setText("STATEMENTS");
        STATEMENTS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                STATEMENTSActionPerformed(evt);
            }
        });
        getContentPane().add(STATEMENTS, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 280, 130, 30));

        BANKACCOUNT.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BANKACCOUNT.setText("BANK ACC");
        BANKACCOUNT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BANKACCOUNTActionPerformed(evt);
            }
        });
        getContentPane().add(BANKACCOUNT, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, 130, 40));

        MPESA2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        MPESA2.setText("M-PESA");
        MPESA2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MPESA2ActionPerformed(evt);
            }
        });
        getContentPane().add(MPESA2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, 130, 30));

        mpesa.setBackground(new java.awt.Color(102, 255, 0));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("M-PESA");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("PAY BILL: 7708545");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("PHONE NO:");

        javax.swing.GroupLayout PHONENOLayout = new javax.swing.GroupLayout(PHONENO);
        PHONENO.setLayout(PHONENOLayout);
        PHONENOLayout.setHorizontalGroup(
            PHONENOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PHONENOLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );
        PHONENOLayout.setVerticalGroup(
            PHONENOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PHONENOLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        phoneno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phonenoActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("ENTER AMOUNT:");

        javax.swing.GroupLayout ENTERAMOUNTLayout = new javax.swing.GroupLayout(ENTERAMOUNT);
        ENTERAMOUNT.setLayout(ENTERAMOUNTLayout);
        ENTERAMOUNTLayout.setHorizontalGroup(
            ENTERAMOUNTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ENTERAMOUNTLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );
        ENTERAMOUNTLayout.setVerticalGroup(
            ENTERAMOUNTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ENTERAMOUNTLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pay.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        pay.setText("PAY");
        pay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mpesaLayout = new javax.swing.GroupLayout(mpesa);
        mpesa.setLayout(mpesaLayout);
        mpesaLayout.setHorizontalGroup(
            mpesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mpesaLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(mpesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(mpesaLayout.createSequentialGroup()
                        .addGroup(mpesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PHONENO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ENTERAMOUNT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(mpesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(phoneno, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(amount, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(113, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mpesaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pay, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(146, 146, 146))
        );
        mpesaLayout.setVerticalGroup(
            mpesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mpesaLayout.createSequentialGroup()
                .addContainerGap(119, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(mpesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PHONENO, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(phoneno, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(mpesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(amount, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ENTERAMOUNT, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(pay, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62))
        );

        jTabbedPane1.addTab("tab1", mpesa);

        bankaccount.setBackground(new java.awt.Color(153, 153, 0));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("BANK ACCOUNT");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("ENTER ACCOUNT NO:");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel12)
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("ENTER AMOUNT:");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel13)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        PAY.setText("PAY");
        PAY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PAYActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bankaccountLayout = new javax.swing.GroupLayout(bankaccount);
        bankaccount.setLayout(bankaccountLayout);
        bankaccountLayout.setHorizontalGroup(
            bankaccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bankaccountLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(bankaccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(85, 85, 85)
                .addGroup(bankaccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(enteraccountno)
                    .addComponent(enteramount, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE))
                .addContainerGap(44, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bankaccountLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(PAY, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74))
        );
        bankaccountLayout.setVerticalGroup(
            bankaccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bankaccountLayout.createSequentialGroup()
                .addContainerGap(98, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(bankaccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(enteraccountno, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63)
                .addGroup(bankaccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(enteramount, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61)
                .addComponent(PAY, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
        );

        jTabbedPane1.addTab("tab2", bankaccount);

        statements.setBackground(new java.awt.Color(204, 0, 204));

        printstatement.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "name", "Amount", "TokenID", "Tokens", "Date"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(printstatement);

        showdata.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        showdata.setText("View");
        showdata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showdataActionPerformed(evt);
            }
        });

        export.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        export.setText("Export");
        export.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exportActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout statementsLayout = new javax.swing.GroupLayout(statements);
        statements.setLayout(statementsLayout);
        statementsLayout.setHorizontalGroup(
            statementsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, statementsLayout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(showdata, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 146, Short.MAX_VALUE)
                .addComponent(export, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, statementsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );
        statementsLayout.setVerticalGroup(
            statementsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statementsLayout.createSequentialGroup()
                .addGap(139, 139, 139)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(statementsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(showdata, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(export, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64))
        );

        jTabbedPane1.addTab("tab3", statements);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(353, 2, 580, 520));

        setSize(new java.awt.Dimension(950, 561));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void DashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DashboardMouseClicked

        // TODO add your handling code here:
    }//GEN-LAST:event_DashboardMouseClicked

    private void HomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeMouseClicked

        dispose();
        tab1 d = new tab1();
        d.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_HomeMouseClicked

    private void PayBillMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PayBillMouseClicked

        dispose();
        tab2 d = new tab2();
        d.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_PayBillMouseClicked

    private void EditProfileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditProfileMouseClicked

        dispose();
        tab3 d = new tab3();
        d.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_EditProfileMouseClicked

    private void ContactUsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ContactUsMouseClicked

        dispose();
        tab4 d = new tab4();
        d.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_ContactUsMouseClicked

    private void LogOutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogOutMouseClicked

               
      int response =  JOptionPane.showConfirmDialog(this,"Do you want to Log Out?","confirm",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        
      if(response==JOptionPane.YES_NO_OPTION){
          dispose ();
          new Loginform().setVisible(true);
      } else if (response==JOptionPane.CANCEL_OPTION){
          
      }
        // TODO add your handling code here:
    }//GEN-LAST:event_LogOutMouseClicked

    private void User2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_User2MouseClicked

        dispose();
        tab5 d = new tab5();
        d.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_User2MouseClicked

    private void MPESA2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MPESA2ActionPerformed

        jTabbedPane1.setSelectedIndex(0);
        // TODO add your handling code here:
    }//GEN-LAST:event_MPESA2ActionPerformed

    private void BANKACCOUNTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BANKACCOUNTActionPerformed

        jTabbedPane1.setSelectedIndex(1);
        
        // TODO add your handling code here:
    }//GEN-LAST:event_BANKACCOUNTActionPerformed

    private void STATEMENTSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_STATEMENTSActionPerformed

        jTabbedPane1.setSelectedIndex(2);
        
     
        // TODO add your handling code here:
    }//GEN-LAST:event_STATEMENTSActionPerformed

    private void phonenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phonenoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phonenoActionPerformed

    private void payActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payActionPerformed

        
        String PHONENO = phoneno.getText();
        int ENTERAMOUNT = Integer.parseInt(amount.getText());//converts string to int

        
        if (PHONENO.isEmpty()|| ENTERAMOUNT == 0){
            JOptionPane.showMessageDialog(null, "Enter phone number and amount");
        } else {
            try {
                
         String CONN_STRING =  "jdbc:mysql://localhost:3306/prepaid water system";
         String USERNAME = "Olang";
         String PASSWORD = "Olang254";
         
         String query = "INSERT INTO paymentdetails VALUES(?,?,?,?,?,?)";
         
         conn = DriverManager.getConnection(CONN_STRING,USERNAME,PASSWORD);
         
         stmt=conn.prepareStatement(query);
         
         int token = ENTERAMOUNT/Rate;
         GregorianCalendar cal =  new GregorianCalendar();
         int date = cal.get(Calendar.YEAR);
         int month = cal.get(Calendar.MONTH)+1;
         
         int day = cal.get(Calendar.DATE);
         
         String d = ""+day+"/"+month+"/"+date+"";
         String e = "1234567890"+"ABCDEFGHIJKLMNOPQRSTUVWXYZ";
         Random rnd = new Random();
         StringBuilder sb = new StringBuilder(10);
         
         for(int i = 0; i<10; i++){
             sb.append(e.charAt(rnd.nextInt(e.length())));
         }
         String random=sb.toString();
        
         stmt.setString(1,getMeterno()); //implememts getter function to get username
         stmt.setInt(2,ENTERAMOUNT);
         stmt.setString(3,random); //inputs token id alson known as transaction code
         stmt.setInt(4,token);
         stmt.setString(5,d);// inputs the date from Gregorian calender in the database
         stmt.setString(6,PHONENO);
         
         stmt.executeUpdate();
         JOptionPane.showMessageDialog(null, "Payment successfull");
            } catch (Exception e){
              System.out.println(e);
              
            }
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_payActionPerformed

    private void PAYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PAYActionPerformed


        String ENTERACCOUNTNO = enteraccountno.getText();
        int ENTERAMOUNT = Integer.parseInt(enteramount.getText());
        
        if (ENTERACCOUNTNO.isEmpty()|| ENTERAMOUNT == 0){
            JOptionPane.showMessageDialog(null, "Enter phone number and amount");
        } else {
            
            try {
                
         String CONN_STRING =  "jdbc:mysql://localhost:3306/prepaid water system";
         String USERNAME = "Olang";
         String PASSWORD = "Olang254";
         
         String query = "INSERT INTO paymentdetails VALUES(?,?,?,?,?,?)";
         
         conn = DriverManager.getConnection(CONN_STRING,USERNAME,PASSWORD);
         
         stmt=conn.prepareStatement(query);
         
         int token = ENTERAMOUNT/Rate;
         GregorianCalendar cal =  new GregorianCalendar();
         int date = cal.get(Calendar.YEAR);
         int month = cal.get(Calendar.MONTH)+1;
         int day = cal.get(Calendar.DATE);
         
         String d = ""+day+"/"+month+"/"+date+"";
         String e = "1234567890"+"ABCDEFGHIJKLMNOPQRSTUVWXYZ";
         Random rnd = new Random();
         StringBuilder sb = new StringBuilder(10);
         
         for(int i = 0; i<10; i++){
             sb.append(e.charAt(rnd.nextInt(e.length())));
         }
         String random=sb.toString();
        
         stmt.setString(1,getMeterno()); //implememts getter function to get username
         stmt.setInt(2,ENTERAMOUNT);
         stmt.setString(3,random); //inputs token id alson known as transaction code
         stmt.setInt(4,token);
         stmt.setString(5,d);// inputs the date from Gregorian calender in the database
         stmt.setString(6,ENTERACCOUNTNO);
         
         stmt.executeUpdate();
         JOptionPane.showMessageDialog(null, "Payment successfull");
            } catch (Exception e){
              System.out.println(e);
              
            }
            
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_PAYActionPerformed

    private void showdataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showdataActionPerformed

        String Username = getMeterno();
       
        try {
                      
         String CONN_STRING =  "jdbc:mysql://localhost:3306/prepaid water system";
         String USERNAME = "Olang";
         String PASSWORD = "Olang254";
         
         String query = "SELECT*FROM paymentdetails WHERE name = ?";
         
         conn = DriverManager.getConnection(CONN_STRING,USERNAME,PASSWORD);
         
         stmt=conn.prepareStatement(query);
         
         stmt.setString(1,Username);
         
         ResultSet rs = stmt.executeQuery();
         
         while(rs.next()){
            String Name = rs.getString("name");
            String Amount = String.valueOf(rs.getInt("amount"));
            String Tokenid = rs.getString("tokenid");
            String Token = String.valueOf(rs.getInt("token"));
            String Date = rs.getString("date");
            
            
            String tbData [] = {Name,Amount,Tokenid,Token,Date};
            DefaultTableModel tblModel = (DefaultTableModel)printstatement.getModel();
            tblModel.addRow(tbData);
             
         }
         
        } catch(Exception e){
            System.out.println(e);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_showdataActionPerformed

    private void exportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exportActionPerformed

        MessageFormat header = new MessageFormat("CLEAN WATER COMPANY YOUR STATAMENTS");
        MessageFormat footer = new MessageFormat("Page(0,number,integer)");
        
        try{
            printstatement.print(JTable.PrintMode.NORMAL, header, footer);
        } catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_exportActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tab2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tab2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tab2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tab2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tab2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BANKACCOUNT;
    private javax.swing.JPanel ContactUs;
    private javax.swing.JPanel Dashboard;
    private javax.swing.JPanel ENTERAMOUNT;
    private javax.swing.JPanel EditProfile;
    private javax.swing.JPanel Header2;
    private javax.swing.JPanel Home;
    private javax.swing.JPanel LogOut;
    private javax.swing.JButton MPESA2;
    private javax.swing.JButton PAY;
    private javax.swing.JPanel PHONENO;
    private javax.swing.JPanel PayBill;
    private javax.swing.JButton STATEMENTS;
    private javax.swing.JPanel User2;
    private javax.swing.JPanel UserMenu;
    private javax.swing.JTextField amount;
    private javax.swing.JPanel bankaccount;
    private javax.swing.JLabel contactus;
    private javax.swing.JLabel dashboard;
    private javax.swing.JLabel editprofile;
    private javax.swing.JTextField enteraccountno;
    private javax.swing.JTextField enteramount;
    private javax.swing.JButton export;
    private javax.swing.JLabel home;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel logout;
    private javax.swing.JPanel mpesa;
    private javax.swing.JButton pay;
    private javax.swing.JLabel paybill;
    private javax.swing.JTextField phoneno;
    private javax.swing.JTable printstatement;
    private javax.swing.JButton showdata;
    private javax.swing.JPanel statements;
    private javax.swing.JLabel user2;
    // End of variables declaration//GEN-END:variables

}
